proyectos_departamento_homepage:
    pattern:  /
    defaults: { _controller: ProyectosDepartamentoBundle:Default:index }

proyectos_departamento_alumnos:
    pattern:  /alumnos/
    defaults: { _controller: ProyectosDepartamentoBundle:Alumnos:index }

proyectos_departamento_alumnos_detalle:
    pattern:  /alumnos/detalle/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Alumnos:detalleAlumno }

proyectos_departamento_alumnos_modificar:
    pattern:  /alumnos/modificar/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Alumnos:modificarAlumno }

proyectos_departamento_alumnos_eliminar:
    pattern:  /alumnos/eliminar/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Alumnos:eliminarAlumnoGet }
    methods:  [GET]

proyectos_departamento_alumnos_eliminar_confirm:
    pattern:   /alumnos/eliminar/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Alumnos:eliminarAlumnoPost }
    methods:   [POST]

proyectos_departamento_alumnos_anadirGet:
    pattern:  /alumnos/anadir/
    defaults: {  _controller: ProyectosDepartamentoBundle:Alumnos:anadirAlumnoGet }
    methods:  [GET]

proyectos_departamento_alumnos_anadirPost:
    pattern:  /alumnos/anadir/
    defaults: {  _controller: ProyectosDepartamentoBundle:Alumnos:anadirAlumnoPost }
    methods:  [POST]

proyectos_departamento_profesores:
    pattern:  /profesores/
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:index }

proyectos_departamento_profesores_anadirGet:
    pattern:  /profesores/anadir/
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:anadirProfesorGet }
    methods:  [GET]

proyectos_departamento_profesores_anadirPost:
    pattern:  /profesores/anadir/
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:anadirProfesorPost }
    methods:  [POST]

proyectos_departamento_profesores_detalle:
    pattern:  /profesores/detalle/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:detalleProfesor }

proyectos_departamento_profesores_modificar:
    pattern:  /profesores/modificar/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:modificarProfesor }

proyectos_departamento_profesores_eliminar:
    pattern:  /profesores/eliminar/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:eliminarProfesorGet }
    methods:  [GET]

proyectos_departamento_profesores_eliminar_confirm:
    pattern:   /profesores/eliminar/{id}
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:eliminarProfesorPost }
    methods:   [POST]