proyectos_departamento_homepage:
    pattern:  /
    defaults: { _controller: ProyectosDepartamentoBundle:Default:index }

proyectos_departamento_alumnos:
    pattern:  /alumnos/
    defaults: { _controller: ProyectosDepartamentoBundle:Alumnos:index }

proyectos_departamento_profesores:
    pattern:  /profesores/
    defaults: { _controller: ProyectosDepartamentoBundle:Profesores:index }